export   const SET_SETTINGS_DATA = 'APP/SET_SETTINGS_DATA';

export   const SET_CART_ITEM = 'APP/SET_CART_ITEM';
export   const ADD_TO_CART = 'APP/ADD_TO_CART';

export   const ADD_TO_CART_SAGA = 'APP/ADD_TO_CART_SAGA';
export   const DECREMENT_CART_SAGA = 'APP/DECREMENT_CART_SAGA';
export   const REQUEST_PRODUCTS_DATA_SAGA = 'APP/REQUEST_PRODUCTS_DATA_SAGA';

export   const INCREMENT_COUNT_CART = 'CART/INCREMENT_COUNT_CART';
export   const DECREMENT_COUNT_CART = 'CART/DECREMENT_COUNT_CART';


export   const SET_PRODUCTS_DATA = 'APP/SET_PRODUCTS_DATA';